name: Deploy to Azure

on:
  push:
    branches:
      - main  # Change this if you're using a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "mirrorbot"  # Replace with your Azure App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Deploy application
        run: |
          git pull
          pip install -r requirements.txt
          chmod +x startup.sh
          ./startup.sh
